---
- name: prepare build
  hosts: build
  become: yes

  tasks:
  - name: Ensure jdk is present
    apt:
      name: default-jdk
      state: present

  - name: Ensure maven is present
    apt:
      name: maven
      state: present
  
  - name: Ensure git is present
    apt:
      name: git
      state: present

  - name: Cloning the repo
    command: git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      chdir: /home/user/

  - name: Artifact generation
    command: mvn package
      chdir: /home/user/boxfuse-sample-java-war-hello/

  - name: Copying an artifact to /tmp
    copy:
      src: /home/user/boxfuse-sample-java-war-hello/target/hello-1.0.war
      dst: /tmp/hello-1.0.war
 
      