---
- name: prepare build
  hosts: build
  become: yes

  tasks:
  - name: Ensure jdk is present
    apt:
      name: default-jdk
      state: present

  - name: Ensure maven is present
    apt:
      name: maven
      state: present
  
  - name: Ensure git is present
    apt:
      name: git
      state: present

  - name: Cloning the repo
    command: git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
    args:
        chdir: /home/user/

  - name: Artifact generation
    command: mvn package
    args:
        chdir: /home/user/boxfuse-sample-java-war-hello/

  - name: Artifact delivery
    synchronize:
    mode: push
    src: //home/user/boxfuse-sample-java-war-hello/target/hello-1.0.war
    dst: rsync://84.201.162.41/tmp/
          
- name: prepare prod
  hosts: prod
  become: yes

- name: Ensure tomcat is started
  service:
    name: tomcat
    state: started

- name: Copying an artifact
  shell: 'cp /tmp/hello-1.0.war /var/lib/tomcat9/webapps/'