---
- name: prepare build
  hosts: build
  become: yes

  tasks:
  - name: Ensure jdk is present
    apt:
      name: default-jdk
      state: present

  - name: Ensure maven is present
    apt:
      name: maven
      state: present
  
  - name: Ensure git is present
    apt:
      name: git
      state: present

  - name: Cloning the repo
    command: git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
    args:
        chdir: /home/user/

  - name: Artifact generation
    command: mvn package
    args:
        chdir: /home/user/boxfuse-sample-java-war-hello/

  - name: Artifact delivery step 1
    copy:
      src: /home/user/boxfuse-sample-java-war-hello/target/hello-1.0.war
      dest: /tmp/hello-1.0.war
          
- name: prepare prod
  hosts: prod
  become: yes

  tasks:
  - name: Ensure tomcat is started
    service:
      name: tomcat
      state: started

  - name: Artifact delivery step 1
    fetch:
      src: /tmp/hello-1.0.war
      dest: /var/lib/tomcat9/webapps/